version: "3"

services:
  app:
    build: .
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=123456

  db: # For local testing
    image: mysql:8
    container_name: db
    restart: alway
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
